name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
          node-version: '12.x'
    - name: npm install
      run: npm ci
    - name: npm test  
      run: npm run test:unit
      env:
        CI: true
